package com.hung.enums;


public enum BusinessTypeEnum {
    SAVING("SAVING", "SAVING"),
    COMBO2("COMBO2", "COMBO2"),
    COMBO3("COMBO3", "COMBO3"),
    COMBO1_EX("COMBO1_EX", "COMBO1_EX"),
    COMBO2_EX("COMBO2_EX", "COMBO2_EX"),
    COMBO3_EX("COMBO3_EX", "COMBO3_EX"),
    CUSTOMER("CUSTOMER", "CUSTOMER"),
    CARD("CARD", "CARD"),
    EBANK("EBANK", "EBANK"),
    SMS("SMS", "SMS"),
    SUPER("SUPER", "SUPER"),
    SUPER_EX("SUPER_EX", "SUPER_EX"),
    CLOSE_SUPER("CLOSE_SUPER", "CLOSE_SUPER"),
    ACC_STATEMENT("ACC_STATEMENT", "ACC_STATEMENT"),
    ACCOUNT_BALANCE("ACCOUNT_BALANCE", "ACCOUNT_BALANCE"),
    OPEN_SAVING("OPEN_SAVING", "OPEN_SAVING"),
    MANAGE_SAVING("MANAGE_SAVING", "MANAGE_SAVING"),
    CASH("CASH", "CASH"),
    FEE("FEE", "FEE"),
    WITHDRAW("WITHDRAW", "WITHDRAW"),
    REVERSE("REVERSE", "REVERSE"),
    TELLERID("TELLERID", "TELLERID"),
    INVENTORY("INVENTORY", "INVENTORY"),
    CHARGE("CHARGE", "CHARGE"),
    CUSTOMS("CUSTOMS", "CUSTOMS"),
    SETTLEMENT("SETTLEMENT", "SETTLEMENT"),
    INVENTORY_R("INVENTORY_R", "INVENTORY_R"),
    INVENTORY_S("INVENTORY_S", "INVENTORY_S"),
    ACQT_TELLER_NHAP("ACQT_TELLER_NHAP", "ACQT_TELLER_NHAP"),
    ACQT_PGD_NHAP("ACQT_PGD_NHAP", "ACQT_PGD_NHAP"),
    ACQT_XUAT_PGD("ACQT_XUAT_PGD", "ACQT_XUAT_PGD"),
    ACQT_XUAT_TELLER("ACQT_XUAT_TELLER", "ACQT_XUAT_TELLER"),
    ACQT_TELLER_XUAT("ACQT_TELLER_XUAT", "ACQT_TELLER_XUAT"),
    ACQT_XUAT_LO("ACQT_XUAT_LO", "ACQT_XUAT_LO"),
    ACQT_HUY_MAT("ACQT_HUY_MAT", "ACQT_HUY_MAT"),
    GIFT_CREATE("GIFT_CREATE", "GIFT_CREATE"),
    GIFT_INPUT("GIFT_INPUT", "GIFT_INPUT"),
    GIFT_TRANSFER ("GIFT_TRANSFER", "GIFT_TRANSFER"),
    GIFT_UPDATE ("GIFT_UPDATE", "GIFT_UPDATE"),
	CREDIT_CARD ("CREDIT_CARD", "CREDIT_CARD");
    private final String code;
    private final String name;

    BusinessTypeEnum(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public String getName() {
        return name;
    }
}
